services:

  _defaults:
    autowire: true

  WArslett\TableBuilder\TableBuilderFactory:

  WArslett\TableBuilder\TableBuilderFactoryInterface:
    alias: WArslett\TableBuilder\TableBuilderFactory

  WArslett\TableBuilder\Twig\StandardTemplatesLoader:
    tags: [ 'twig.loader' ]

  WArslett\TableBuilder\RouteGeneratorAdapter\SprintfAdapter:

  WArslett\TableBuilder\RouteGeneratorAdapter\SymfonyRoutingAdapter:

  WArslett\TableBuilder\RouteGeneratorAdapter\RouteGeneratorAdapterInterface:
    alias: WArslett\TableBuilder\RouteGeneratorAdapter\SymfonyRoutingAdapter

  WArslett\TableBuilder\Renderer\Html\PhtmlRenderer:

  WArslett\TableBuilder\Renderer\Html\TwigRenderer:
    arguments:
      $themeTemplatePath: 'table-builder/standard.html.twig'

  WArslett\TableBuilder\Renderer\Html\HtmlTableRendererInterface:
    alias: WArslett\TableBuilder\Renderer\Html\TwigRenderer

  WArslett\TableBuilder\Twig\TableRendererExtension:
    tags: [ 'twig.extension' ]
